apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anzo-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anzo-operator
subjects:
- kind: ServiceAccount
  name: anzo-operator
