apiVersion: anzo.cambridgesemantics.com/v1
kind: Anzo
metadata:
  name: agent01
spec:
  nodeConfig:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: anzo
      serviceName: anzo-agent01
      template:
        metadata:
          labels:
            app: anzo
        spec:
          containers:
          - image: registry.connect.redhat.com/cambridgesemantics/anzo@sha256:af0fe5361938ef891432796b45aa409ff4367adf42bf33cd8dac3edf3bcb6e47
            name: anzo
            resources:
              limits:
                cpu: 4000m
                memory: 12Gi
              requests:
                cpu: 4000m
                memory: 12Gi
          serviceAccountName: anzo-operator
  role: AnzoAgent
status: {}
