apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: anzo-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_ANZO
          value: registry.connect.redhat.com/cambridgesemantics/anzo@sha256:af0fe5361938ef891432796b45aa409ff4367adf42bf33cd8dac3edf3bcb6e47
        image: registry.connect.redhat.com/cambridgesemantics/anzo-operator@sha256:45f082056d6bb8a88cbcdf8ee30021de757e39ddfe71ccbf2dfd8e54159c53e0
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: anzo-operator
      terminationGracePeriodSeconds: 10
